### ISSUE TITLE
홈페이지에서의 웹 표준, 웹 접근성, 검색 엔진 최적화 작업 진행 Refactor

### ISSUE THREAD

**Issue by joyswim** [prgrms-fe-devcourse/FEDC5_looky_heejin#107]
# 📌간단한 기능 설명
홈페이지, 알림 페이지의 웹 표준, 웹 접근성, 검색 엔진 최적화 작업을 진행합니다.
- 웹 표준
- 웹 접근성
- 검색 엔진 최적화(SEO)

# 📄Todo
- [x] 웹 접근성 최적화
    - [x] 키보드 네비게이션 적용
    - [x] 접근 가능한 이름(Accessible Name) 추가  
    - [x] 모달 포커스 트랩 적용
- [x]  검색 엔진 최적화(SEO)
    - [x]  <meta> description, keywords 추가
    - [x]  robots.txt 추가
    AuthRoute 페이지의 크롤링을 방지한다. 

# 🔗레퍼런스
[검색 엔진 최적화(SEO) / The Open Graph protocol](https://ogp.me/)
[검색 엔진 최적화(SEO) / robots.txt](https://developers.google.com/search/docs/crawling-indexing/robots/intro?hl=ko)
[focus-trap-react 라이브러리](https://www.npmjs.com/package/focus-trap-react)
