### ISSUE TITLE
Vitest 설치

### ISSUE THREAD

**Issue by SoJuSo** [prgrms-fe-devcourse/FEDC5_looky_heejin#119]
# 📌간단한 기능 설명
테스트를 위한 유닛 테스트 라이브러리 Vitest를 설치하고 기타 설정을 추가합니다.

# 📄Todo
- [ ] Vitest 설치
- [ ] 라우팅 관련 test 기능 셋업
- [ ] 컴포넌트 관련 test 셋업
- [ ] 페이지단위 test 셋업

<br />
> 브랜치 명시 규칙
${issue번호}/${작업 내용 혹은 컴포넌트 내용}
ex) refactor/123-infinityScroll
