### ISSUE TITLE
홈페이지 성능 최적화 Refactor

### ISSUE THREAD

**Issue by joyswim** [prgrms-fe-devcourse/FEDC5_looky_heejin#125]
# 📌간단한 기능 설명
HomePage LightHouse 기준 성능 최적화를 진행한다.
⚠️ package.json이 변경되었습니다.
리소스 압축 vite-plugin-compression이 설치되었습니다. 머지 후 `npm i`를 실행해주세요.

# 📄Todo
- [x] Image 컴포넌트 교체
- [x] 지연 로드와 코드 스플리팅 lazy, Suspense 적용
라우팅 페이지, 모달 뷰 컴포넌트에 적용
- [x] 리소스 압축 vite-plugin-compression 라이브러리 사용
- [x] Icon 이미지 스프라이트

# 📜 레퍼런스
[프론트엔드 웹 성능 최적화 방법은 뭐가 있을까?](https://klmhyeonwooo.tistory.com/70)
[이미지 스프라이트 기법](https://velog.io/@untiring_dev/HTMLCSS-Day31.-%EC%9D%B4%EB%AF%B8%EC%A7%80-%EC%8A%A4%ED%94%84%EB%9D%BC%EC%9D%B4%ED%8A%B8-%EA%B8%B0%EB%B2%95)
